### ISSUE TITLE
应当阻止用户创建奇怪的自定义文件 

### ISSUE THREAD

**Issue by Apolsus** [gmshrek/info#15]
我使用右键助手自定义一个文件类型，名称为 '.'
这是一个系统保留文件，指向本文件夹。
这么做的后果就是，我不小心点到新建 '.'，然后他把我的文件夹清空啦！！！！！

**Comment by gmshrek** [comment]
您好，感谢您的反馈，我们会在下个版本修复此问题，给您带来的不变深感抱歉！



| |
gmshrek
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年07月22日 16:14 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [gmshrek/info] 应当阻止用户创建奇怪的自定义文件 (Issue #15) |

我使用右键助手自定义一个文件类型，名称为 '.'
这是一个系统保留文件，指向本文件夹。
这么做的后果就是，我不小心点到新建 '.'，然后他把我的文件夹清空啦！！！！！
