### ISSUE TITLE
Font and theme customization?

### ISSUE THREAD

**Issue by pramjan90** [gmshrek/info#16]
Hi There,

A beautiful app you have created, really well done!

I would like to request if we could could have a feature for customizing the fonts and colors. I think this can be done either by having:
- CSS for controlling the font and colors of the rendered document
- Menu options for choosing book and code fonts.

Thank you for the consideration, hope you can help add these features!

**Comment by pramjan90** [comment]
Hi, I see you've provided some nice features in the recent update to the app. Is there any consideration for fonts? I think it would be really beneficial for the readers!

**Comment by gmshrek** [comment]
Hello


Thank you for your feedback! We took your advice and will add it in the next version!


| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Pramod ***@***.***> |
| Date | 01/9/2023 01:23 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [gmshrek/info] Font and theme customization? (Issue #16) |

Hi, I see you've provided some nice features in the recent update to the app. Is there any consideration for fonts? I think it would be really beneficial for the readers!

**Comment by pramjan90** [comment]
Hi,
Thank you for the new update with the font selection drop down!

I see one bug though - I'm unable to scroll down in the drop down menu, so its only showing a few of the fonts I've got on my system. Can you please fix this?

Thanks!

**Comment by pramjan90** [comment]
Hi @gmshrek,

Trust you are doing well!

- Is it possible to include the selected font in the exported PDFs as well?
- Also please translate the Chinese text in the font selection dialog to English for the sake of English speakers.

Thanks!

**Comment by gmshrek** [comment]
Hello, thank you for your feedback again!

1, No problem, next version update.

2. The dialog box is displayed in English. Can you take a screenshot to see which one to go to?

| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Pramod ***@***.***> |
| Date | 02/16/2023 18:01 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/info] Font and theme customization? (Issue #16) |

Hi @gmshrek,

Trust you are doing well!

Is it possible to include the selected font in the exported PDFs as well?
Also please translate the Chinese text in the font selection dialog to English for the sake of English speakers.

Thanks!

**Comment by pramjan90** [comment]
Hi!

Many thanks for the quick response - this is great support!

This is the dialog box that I get when I click on the "Font" option in the toolbar:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/13656157/219707150-3dd74743-35df-4e62-bf2c-01ec590af640.png">

The two options are shown in Chinese language (although I can somewhat guess what they could be).

Cheers!

**Comment by pramjan90** [comment]
Thanks so much for the quick support on these issues!
The app looks great now!
