### ISSUE TITLE
进入 iterm2 会创建额外的窗口

### ISSUE THREAD

**Issue by Apolsus** [gmshrek/info#23]
我的 iterm2 不是常驻后台的，我打开了 iterm2 在启动时开启一个窗口的选项。这导致如果我从文件夹进入，就会一次打开两个窗口。但如果我关闭这一选项，我在聚焦当中开启 iterm2 就需要输入两次才会有一个窗口。

**Comment by gmshrek** [comment]
您好，这是 iTerm2 设置的问题，您可以进入 iTerm2 的偏好设置 -> General -> Startup -> 将 Window restoration policy 项设置为：Only Restore Hotkey Window 即可。

**Comment by Apolsus** [comment]
啊不，应该是系统设置里退出程序时候自动关闭窗口这里的问题。已经解决了。

**Comment by Apolsus** [comment]
[更完美的解决方案](https://gitlab.com/gnachman/iterm2/-/issues/6562#:~:text=I%20found%20a,Hope%20it%20helps!)，不需要修改 MacOS 系统设置
