### ISSUE TITLE
JSON格式化工具 树状视图能否增加节点的 key value 复制功能

### ISSUE THREAD

**Issue by zeroskylian** [gmshrek/info#40]
https://apps.apple.com/us/app/visual-json/id488709442?l=zh-Hans-CN&mt=12

类似于 visual json

**Comment by gmshrek** [comment]
可以的，感谢您的反馈


| |
gmshrek
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月25日 11:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [gmshrek/info] JSON格式化工具 树状视图能否增加节点的 key value 复制功能 (Issue #40) |

https://apps.apple.com/us/app/visual-json/id488709442?l=zh-Hans-CN&mt=12

类似于 visual json

**Comment by zeroskylian** [comment]
好的，期待你的下一的版本

**Comment by zeroskylian** [comment]
非常感谢大佬的更新，但是能否再支持下单独的 key value 的复制，现在 复制出来的是key: value
