### ISSUE TITLE
Finder 扩展启用以后，外置磁盘的图标就异常

### ISSUE THREAD

**Issue by l782993610** [gmshrek/info#5]
问题：Finder 扩展启用以后，外置磁盘的图标就变成一个未知文件的图标。这与 Keka 的作者遇到的问题是一样的，那位作者提供一个选项关闭以关闭在外置磁盘的扩展启用。我想这一定就是昨天的更新导致的。因为上面写着“外置磁盘 新增右键功能”

系统：Big Sur 11.4

机器：MBP M1 2020

**Comment by gmshrek** [comment]
您好，非常感谢您的反馈，我们会在下个版本加入相应的配置项！


| |
gmshrek
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年07月19日 ***@***.***> 写道：

问题：Finder 扩展启用以后，外置磁盘的图标就变成一个未知文件的图标。这与 Keka 的作者遇到的问题是一样的，那位作者提供一个选项关闭以关闭在外置磁盘的扩展启用。我想这一定就是昨天的更新导致的。因为上面写着“外置磁盘 新增右键功能”

系统：Big Sur 11.4

机器：MBP M1 2020
